/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controllers.DangNhapController;
import Controllers.LinhKienController;
import Models.LinhKien;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import org.w3c.dom.events.MouseEvent;

/**
 *
 * @author ddom6
 */
public final class TrangChu extends javax.swing.JFrame {

    private DangNhapController dangNhapController;
    private LinhKienController linhKienController;
    private String TaiKhoan;
    private String MatKhau;

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();

//        ListPhong.setComponentPopupMenu(PopupMenuPhong);
        PopupMenu();
        LoadData();
    }

    public TrangChu(String TK, String MK) {
        initComponents();
        this.TaiKhoan = TK;
        this.MatKhau = MK;
        PopupMenu();
        LoadData();
    }

    public void PopupMenu() {
        Component[] component = ListPhong.getComponents();
        for (int i = 0; i < component.length; i++) {
            if (component[i] instanceof JButton) {
                JButton button = (JButton) component[i];
                String CurrentBtn = button.getText();

                button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        dispose();
                        if (cbHang.getSelectedItem() == "Tất cả") {
                            frmThanhToan fThanhToan = new frmThanhToan(TaiKhoan, MatKhau, CurrentBtn, null);
                            fThanhToan.setLocationRelativeTo(null);
                            fThanhToan.setVisible(true);
                        } else {
                            frmThanhToan fThanhToan = new frmThanhToan(TaiKhoan, MatKhau, CurrentBtn, cbHang.getSelectedItem().toString());
                            fThanhToan.setLocationRelativeTo(null);
                            fThanhToan.setVisible(true);
                        }

                    }

                });

                button.addMouseListener(new MouseListener() {

                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent e) {

                    }

                    @Override
                    public void mousePressed(java.awt.event.MouseEvent e) {
                        if (SwingUtilities.isRightMouseButton(e)) { // if right click

                            button.setComponentPopupMenu(PopupMenuPhong);

                        }
                    }

                    @Override
                    public void mouseReleased(java.awt.event.MouseEvent e) {
                    }

                    @Override
                    public void mouseEntered(java.awt.event.MouseEvent e) {
                    }

                    @Override
                    public void mouseExited(java.awt.event.MouseEvent e) {
                    }
                });
            }

        }

    }

    public void LoadData() {
        dangNhapController = new DangNhapController();
        linhKienController = new LinhKienController();
        cbHang.removeAllItems();

        List<String> listHang = linhKienController.GetAllHang();

        cbHang.addItem("Tất cả");

        for (String hang : listHang) {
            cbHang.addItem(hang);
        }

        if (dangNhapController.GetRoleCurrentAcount(TaiKhoan, MatKhau).equals("ADMIN")) {
            btnStatistic.setEnabled(true);
        } else if (dangNhapController.GetRoleCurrentAcount(TaiKhoan, MatKhau).equals("USER")) {
            btnStatistic.setEnabled(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupMenuPhong = new javax.swing.JPopupMenu();
        menuThanhToan = new javax.swing.JMenuItem();
        menuQLLK = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnQLLK = new javax.swing.JButton();
        btnNhapLK = new javax.swing.JButton();
        btnStatistic = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        ListPhong = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        cbHang = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemQLLK = new javax.swing.JMenuItem();
        MenuitemQLLKDaNhap = new javax.swing.JMenuItem();
        MenuItemQLLKDaBan = new javax.swing.JMenuItem();
        MenuitemQLMaGiamGia = new javax.swing.JMenuItem();
        MenuitemThanhToan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnLogOut_Toolbar = new javax.swing.JMenuItem();
        frmChangePassword = new javax.swing.JMenuItem();

        menuThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuThanhToan.setText("Thanh toán");
        menuThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThanhToanActionPerformed(evt);
            }
        });
        PopupMenuPhong.add(menuThanhToan);

        menuQLLK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuQLLK.setText("Quản lý linh kiện");
        menuQLLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQLLKActionPerformed(evt);
            }
        });
        PopupMenuPhong.add(menuQLLK);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");
        setSize(new java.awt.Dimension(750, 700));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LINH KIỆN TÍN THÀNH");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 760, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Java\\Baocao\\QuanlyKhachsan\\src\\main\\java\\imgs\\mau_background_don_gian_11_768x536_bffdffbf5cd74dc4a3426fdccc2d180f_master.jpg")); // NOI18N
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 2, -1, 70));

        btnHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon("D:\\Java\\Baocao\\QuanlyKhachsan\\src\\main\\java\\imgs\\Home.png")); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnQLLK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQLLK.setIcon(new javax.swing.ImageIcon("D:\\Java\\Baocao\\QuanlyKhachsan\\src\\main\\java\\imgs\\room.png")); // NOI18N
        btnQLLK.setText("Quản lý linh kiện");
        btnQLLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLLKActionPerformed(evt);
            }
        });

        btnNhapLK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNhapLK.setIcon(new javax.swing.ImageIcon("D:\\Java\\Baocao\\QuanlyKhachsan\\src\\main\\java\\imgs\\multiple-users-silhouette.png")); // NOI18N
        btnNhapLK.setText("Nhập linh kiện");
        btnNhapLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLKActionPerformed(evt);
            }
        });

        btnStatistic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnStatistic.setIcon(new javax.swing.ImageIcon("D:\\Java\\Baocao\\QuanlyKhachsan\\src\\main\\java\\imgs\\trend.png")); // NOI18N
        btnStatistic.setText("Thống kê");
        btnStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon("D:\\Java\\Baocao\\QuanlyKhachsan\\src\\main\\java\\imgs\\logout2.png")); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLLK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNhapLK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStatistic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome)
                    .addComponent(btnQLLK)
                    .addComponent(btnNhapLK)
                    .addComponent(btnStatistic)
                    .addComponent(btnLogout))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ListPhong.setBackground(new java.awt.Color(204, 204, 204));
        ListPhong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách các linh kiện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\CNPM\\Baocao\\QLCuaHangBanLKDT\\src\\main\\java\\imgs\\phone-case.png")); // NOI18N
        jButton1.setText("Màn hình");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(110, 33));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("D:\\Java\\Baocao\\QuanlyKhachsan\\src\\main\\java\\imgs\\living-room.png")); // NOI18N
        jButton2.setText("Camera");
        jButton2.setBorder(null);
        jButton2.setPreferredSize(new java.awt.Dimension(110, 33));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("D:\\CNPM\\Baocao\\QLCuaHangBanLKDT\\src\\main\\java\\imgs\\phone-charger.png")); // NOI18N
        jButton4.setText("Main");
        jButton4.setBorder(null);
        jButton4.setPreferredSize(new java.awt.Dimension(110, 33));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("D:\\CNPM\\Baocao\\QLCuaHangBanLKDT\\src\\main\\java\\imgs\\pin.png")); // NOI18N
        jButton3.setText("Pin");
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.setPreferredSize(new java.awt.Dimension(110, 33));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("D:\\Java\\Baocao\\QuanlyKhachsan\\src\\main\\java\\imgs\\living-room.png")); // NOI18N
        jButton5.setText("Loa");
        jButton5.setBorder(null);
        jButton5.setPreferredSize(new java.awt.Dimension(110, 33));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActonPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("D:\\Java\\Baocao\\QuanlyKhachsan\\src\\main\\java\\imgs\\living-room.png")); // NOI18N
        jButton6.setText("Vỏ");
        jButton6.setBorder(null);
        jButton6.setPreferredSize(new java.awt.Dimension(110, 33));

        javax.swing.GroupLayout ListPhongLayout = new javax.swing.GroupLayout(ListPhong);
        ListPhong.setLayout(ListPhongLayout);
        ListPhongLayout.setHorizontalGroup(
            ListPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPhongLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(ListPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(131, 131, 131)
                .addGroup(ListPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125)
                .addGroup(ListPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListPhongLayout.setVerticalGroup(
            ListPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListPhongLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(ListPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(ListPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        cbHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Hãng");

        jMenuBar1.setMinimumSize(new java.awt.Dimension(249, 40));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(221, 35));

        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Quản lý");
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        MenuItemQLLK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuItemQLLK.setText("Quản lý linh kiện");
        MenuItemQLLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemQLLKActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemQLLK);

        MenuitemQLLKDaNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuitemQLLKDaNhap.setText("Quản lý nhập linh kiện");
        MenuitemQLLKDaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuitemQLLKDaNhapActionPerformed(evt);
            }
        });
        jMenu1.add(MenuitemQLLKDaNhap);

        MenuItemQLLKDaBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuItemQLLKDaBan.setText("Quản linh kiện đã bán");
        MenuItemQLLKDaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemQLLKDaBanActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemQLLKDaBan);

        MenuitemQLMaGiamGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuitemQLMaGiamGia.setText("Quản lý mã giảm giá");
        MenuitemQLMaGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuitemQLMaGiamGiaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuitemQLMaGiamGia);

        MenuitemThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuitemThanhToan.setText("Thanh toán");
        MenuitemThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuitemThanhToanActionPerformed(evt);
            }
        });
        jMenu1.add(MenuitemThanhToan);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("Thống kê");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3.setText("Thống kê doanh thu, chi tiêu");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(51, 51, 51));
        jMenu3.setText("Hệ thống");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        btnLogOut_Toolbar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogOut_Toolbar.setText("Đăng xuất");
        btnLogOut_Toolbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOut_ToolbarActionPerformed(evt);
            }
        });
        jMenu3.add(btnLogOut_Toolbar);

        frmChangePassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        frmChangePassword.setText("Đổi mật khẩu");
        frmChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmChangePasswordActionPerformed(evt);
            }
        });
        jMenu3.add(frmChangePassword);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(40, 40, 40)
                .addComponent(cbHang, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(ListPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn đăng xuất không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            try {
                DangNhap dangNhap = new DangNhap();
                dangNhap.setLocationRelativeTo(null);
                dangNhap.setVisible(true);

            } catch (NoSuchAlgorithmException | UnsupportedEncodingException | InvalidKeyException | NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException ex) {
                Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TrangChu trangchu = new TrangChu(TaiKhoan, MatKhau);
        trangchu.setLocationRelativeTo(this);
        trangchu.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnNhapLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLKActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmLinhKienNhap fLinhKienNhap = new frmLinhKienNhap(TaiKhoan, MatKhau);
        fLinhKienNhap.setLocationRelativeTo(this);
        fLinhKienNhap.setVisible(true);
    }//GEN-LAST:event_btnNhapLKActionPerformed

    private void btnQLLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLLKActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmQLLinhKien fQLLinhKien = new frmQLLinhKien(TaiKhoan, MatKhau, null, null);
        fQLLinhKien.setLocationRelativeTo(this);
        fQLLinhKien.setVisible(true);
    }//GEN-LAST:event_btnQLLKActionPerformed

    private void MenuItemQLLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemQLLKActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmQLLinhKien fQLLinhKien = new frmQLLinhKien(TaiKhoan, MatKhau, null, null);
        fQLLinhKien.setLocationRelativeTo(this);
        fQLLinhKien.setVisible(true);
    }//GEN-LAST:event_MenuItemQLLKActionPerformed

    private void btnLogOut_ToolbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOut_ToolbarActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn đăng xuất không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            try {
                DangNhap dangNhap = new DangNhap();
                dangNhap.setLocationRelativeTo(null);
                dangNhap.setVisible(true);
            } catch (NoSuchAlgorithmException | UnsupportedEncodingException | InvalidKeyException | NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException ex) {
                Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLogOut_ToolbarActionPerformed

    private void frmChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmChangePasswordActionPerformed
        // TODO add your handling code here:

        this.dispose();
        frmChangePassword fChangePassword = new frmChangePassword(TaiKhoan, MatKhau);
        fChangePassword.setLocationRelativeTo(this);
        fChangePassword.setVisible(true);

    }//GEN-LAST:event_frmChangePasswordActionPerformed

    private void menuQLLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQLLKActionPerformed
        // TODO add your handling code here:

        JButton invoker = (JButton) PopupMenuPhong.getInvoker();
        String CurrentBtn = invoker.getText();

        this.dispose();

        if (cbHang.getSelectedItem() == "Tất cả") {
            frmQLLinhKien fQLLinhKien = new frmQLLinhKien(TaiKhoan, MatKhau, CurrentBtn, null);
            fQLLinhKien.setLocationRelativeTo(this);
            fQLLinhKien.setVisible(true);
        } else {
            frmQLLinhKien fQLLinhKien = new frmQLLinhKien(TaiKhoan, MatKhau, CurrentBtn, cbHang.getSelectedItem().toString());
            fQLLinhKien.setLocationRelativeTo(this);
            fQLLinhKien.setVisible(true);
        }

    }//GEN-LAST:event_menuQLLKActionPerformed

    private void menuThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThanhToanActionPerformed
        // TODO add your handling code here:
        JButton invoker = (JButton) PopupMenuPhong.getInvoker();
        String CurrentBtn = invoker.getText();

        this.dispose();

        if (cbHang.getSelectedItem() == "Tất cả") {
            frmThanhToan fThanhToan = new frmThanhToan(TaiKhoan, MatKhau, CurrentBtn, null);
            fThanhToan.setLocationRelativeTo(null);
            fThanhToan.setVisible(true);
        } else {
            frmThanhToan fThanhToan = new frmThanhToan(TaiKhoan, MatKhau, CurrentBtn, cbHang.getSelectedItem().toString());
            fThanhToan.setLocationRelativeTo(null);
            fThanhToan.setVisible(true);
        }

    }//GEN-LAST:event_menuThanhToanActionPerformed

    private void MenuItemQLLKDaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemQLLKDaBanActionPerformed
        // TODO add your handling code here:

        this.dispose();
        frmQLLinhKienDaBan fKienDaBan = new frmQLLinhKienDaBan(TaiKhoan, MatKhau);
        fKienDaBan.setLocationRelativeTo(null);
        fKienDaBan.setVisible(true);

    }//GEN-LAST:event_MenuItemQLLKDaBanActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmThongKe fThongKeDoanhSo = new frmThongKe(TaiKhoan, MatKhau);
        fThongKeDoanhSo.setLocationRelativeTo(this);
        fThongKeDoanhSo.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MenuitemQLLKDaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuitemQLLKDaNhapActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmLinhKienNhap fLinhKienNhap = new frmLinhKienNhap(TaiKhoan, MatKhau);
        fLinhKienNhap.setLocationRelativeTo(this);
        fLinhKienNhap.setVisible(true);

    }//GEN-LAST:event_MenuitemQLLKDaNhapActionPerformed

    private void MenuitemQLMaGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuitemQLMaGiamGiaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmQLMaGiamGia fLMaGiamGia = new frmQLMaGiamGia(TaiKhoan, MatKhau);
        fLMaGiamGia.setLocationRelativeTo(this);
        fLMaGiamGia.setVisible(true);
    }//GEN-LAST:event_MenuitemQLMaGiamGiaActionPerformed

    private void btnStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticActionPerformed
        // TODO add your handling code here:

        if (dangNhapController.GetRoleCurrentAcount(TaiKhoan, MatKhau).equals("ADMIN")) {
            this.dispose();
            frmThongKe fThongKeDoanhSo = new frmThongKe(TaiKhoan, MatKhau);
            fThongKeDoanhSo.setLocationRelativeTo(null);
            fThongKeDoanhSo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Chỉ ADMIN mới được sử dụng chức năng này", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnStatisticActionPerformed

    private void jButton5ActonPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActonPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActonPerformed

    private void MenuitemThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuitemThanhToanActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmThanhToan fThanhToan = new frmThanhToan(TaiKhoan, MatKhau, null, null);
        fThanhToan.setLocationRelativeTo(null);
        fThanhToan.setVisible(true);
    }//GEN-LAST:event_MenuitemThanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                try {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;

            }
        }

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrangChu trangChu = new TrangChu();
                trangChu.setLocationRelativeTo(null);
                trangChu.setVisible(true);

            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListPhong;
    private javax.swing.JMenuItem MenuItemQLLK;
    private javax.swing.JMenuItem MenuItemQLLKDaBan;
    private javax.swing.JMenuItem MenuitemQLLKDaNhap;
    private javax.swing.JMenuItem MenuitemQLMaGiamGia;
    private javax.swing.JMenuItem MenuitemThanhToan;
    private javax.swing.JPopupMenu PopupMenuPhong;
    private javax.swing.JButton btnHome;
    private javax.swing.JMenuItem btnLogOut_Toolbar;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNhapLK;
    private javax.swing.JButton btnQLLK;
    private javax.swing.JButton btnStatistic;
    private javax.swing.JComboBox<String> cbHang;
    private javax.swing.JMenuItem frmChangePassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem menuQLLK;
    private javax.swing.JMenuItem menuThanhToan;
    // End of variables declaration//GEN-END:variables
}
